cldap_ping.c: add missing <sys/types.h> include
Fixes:

cldap_ping.c: In function ‘read_dns_string’:
cldap_ping.c:72:37: error: ‘u_char’ undeclared (first use in this function)

when building with the musl C library, but even with glibc u_char is
defined in <sys/types.h>, it happens to work with glibc <sys/types.h>
gets included by another header.

Reviewed-by: Paulo Alcantara (Red Hat) <pc@manguebit.com>
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@bootlin.com>
Signed-off-by: Steve French <stfrench@microsoft.com>